###########
# site.url, site.title

title: 'Nick Foti'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: 
url:  'http://nfoti.github.io'

me-img: "/img/foti_self_200x200.jpg"
departments: ["Department of Statistics",
              "Institute for Learning and Brain Sciences"]
institution: "University of Washington"

blog-in-social: false
blog-url: ""

email-in-social: true
email: "nfoti at uw dot edu"

keybase-in-social: true
keybase-username: nfoti

social:
  - title: "twitter"
    url: "https://twitter.com/nickfoti_"
  - title: "github"
    url: "https://github.com/nfoti"
  - title: "bitbucket"
    url: "https://bitbucket.org/nfoti"


########
# more settings

gems:
  - 'jekyll-scholar'
  - 'jekyll-paginate'
  - 'jekyll-gist'

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- Makefile
- new_post.sh
- Gemfile
- Gemfile.lock

safe: true
lsi: false

paginate: 10

#######
# plugins

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: foti_cv.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: true
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
