
# Dependencies
#markdown:         redcarpet
#highlighter:      pygments
kramdown:
    input: GFM
    hard_wrap: false

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nick Foti
tagline:          'tagline'
description:      'description'
url:              '' #https://hyde.getpoole.com
baseurl:          / # maybe needs to be ''

author:
  name:           'Nick Foti'
  url:            https://nfoti.github.io
  email:          'nfoti at uw dot edu'

#paginate:         5

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
